### ISSUE TITLE
corejs and jasmine conflict 

### ISSUE THREAD

**Issue by 14Muhammad** [gevgeny/angular2-highcharts#69]
I'm using angular2 version 2.0.0 with angular2-highcharts 0.3.2
I'm getting these error on npm start:
`
node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'.
typings/globals/core-js/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'.
typings/globals/jasmine/index.d.ts(74,9): error TS2375: Duplicate number index signature.
typings/globals/jasmine/index.d.ts(128,9): error TS2374: Duplicate string index signature.
`
Regards ,
Ali

**Comment by renehamburger** [comment]
This is due to a conflict between the typings installed by angular2-highcharts and those in your own project. The automatic installation of typings has just been removed in #68, which should resolve your issue too. Try installing the current master branch to see if it does.

**Comment by gevgeny** [comment]
Hm. v0.3.2 already has this fix afaik

**Comment by renehamburger** [comment]
But there is no 0.3.2 tag, so maybe @14Muhammad is actually using 0.3.1?

**Comment by gevgeny** [comment]
I have not created a tag but published to npm. Will create the tag

**Comment by 14Muhammad** [comment]
@renehamburger @gevgeny  , I just confirmed that I am using **0.3.2**, but still facing same issue.

**Comment by gevgeny** [comment]
hm, @Fank any ideas ?

**Comment by fank** [comment]
I still follow this issue, may have a solution for it. Take a look in it later.

**Comment by renehamburger** [comment]
On a related issue, the highcharts typings in use are somewhat out of date (4.1.9 rather than [4.2.5](https://www.npmjs.com/package/@types/highcharts)). Would it be possible to move away from typings.json altogether and install all types via `npm install @types/...`? That might also resolve @14Muhammad's issue.

**Comment by tmfcosta** [comment]
Same issue here:
 node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'. typings/globals/core-js/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'. typings/globals/jasmine/index.d.ts(74,9): error TS2375: Duplicate number index signature. typings/globals/jasmine/index.d.ts(128,9): error TS2374: Duplicate string index signature.

package.json content:
"scripts": {
    "build": "rm -rf dist && tsc",
    "test": "karma start karma.conf.js",
    "typings-install": "typings install",
    "watch": "ntsc -w"
  },

**Comment by fank** [comment]
@tmfcosta plz remove your node_modules folder and do a "npm install" again, this should fix you problem.

**Comment by scandinave** [comment]
@Fank Done full clean of npm but still the same issue

**Comment by mikesnare** [comment]
Same issue here.  Was using 766a61afe1d55b7c50aa744ecd4adc966dc8df3b to avoid the duplicate identifier issues, but was seeing the issue with the postinstall.  Tried upgrading to 0.3.2 but the identifier issues come back.

FWIW, this most definitely started with 2d17e16814a6f10df5bbcfefcd9bc5fe6c44ae6b.  The previous commit 751cfb7494fe37dbc435ba20ad96de75fd79e05c does not have this issue.  All sorts of upgrades came in the latter commit (including TypeScript itself).  Are all these necessary?

**Comment by tmfcosta** [comment]
@Fank removing node_modules and making a "clean" "npm install" doesn't fix it

**Comment by fank** [comment]
@mikesnare thanks for the info, i think i know what the problem is. Will open a PR these days.

**Comment by monica11** [comment]
@Fank The workaround which i did was to remove the es6-shim folder from the typings and any other related references for the same, Can you do that and push it into master.

**Comment by fank** [comment]
So i tried to check something, but nope everything looks fine.
This is the current version 0.3.2:

```
node_modules/angular2-highcharts$ tree
.
├── dist
│   ├── ChartComponent.d.ts
│   ├── ChartComponent.js
│   ├── ChartComponent.js.map
│   ├── ChartComponent.spec.d.ts
│   ├── ChartComponent.spec.js
│   ├── ChartComponent.spec.js.map
│   ├── ChartEvent.d.ts
│   ├── ChartEvent.js
│   ├── ChartEvent.js.map
│   ├── ChartPointComponent.d.ts
│   ├── ChartPointComponent.js
│   ├── ChartPointComponent.js.map
│   ├── ChartSeriesComponent.d.ts
│   ├── ChartSeriesComponent.js
│   ├── ChartSeriesComponent.js.map
│   ├── ChartXAxisComponent.d.ts
│   ├── ChartXAxisComponent.js
│   ├── ChartXAxisComponent.js.map
│   ├── ChartYAxisComponent.d.ts
│   ├── ChartYAxisComponent.js
│   ├── ChartYAxisComponent.js.map
│   ├── createBaseOpts.d.ts
│   ├── createBaseOpts.js
│   ├── createBaseOpts.js.map
│   ├── deepAssign.d.ts
│   ├── deepAssign.js
│   ├── deepAssign.js.map
│   ├── Highcharts.d.ts
│   ├── Highcharts.js
│   ├── Highcharts.js.map
│   ├── HighchartsService.d.ts
│   ├── HighchartsService.js
│   ├── HighchartsService.js.map
│   ├── index.d.ts
│   ├── index.js
│   ├── index.js.map
│   ├── initChart.d.ts
│   ├── initChart.js
│   ├── initChart.js.map
│   ├── Mocks.d.ts
│   ├── Mocks.js
│   ├── Mocks.js.map
│   ├── stub.d.ts
│   ├── stub.js
│   └── stub.js.map
├── index.d.ts
├── index.js
├── LICENSE
├── package.json
├── README.md
├── tsconfig.json
├── tslint.json
└── typings.json
```

The comments
- https://github.com/gevgeny/angular2-highcharts/issues/69#issuecomment-250134425
- https://github.com/gevgeny/angular2-highcharts/issues/69#issue-179614411

shows that there is a typings folder in the main folder, yea it was before https://github.com/gevgeny/angular2-highcharts/pull/68 but this is fixed since 0.3.2 .

To everyone here please validate that you use a version >=0.3.2

**Comment by fank** [comment]
Ill close this issue because i can't reproduce it, if someone still have issue validate that the angular2-highcharts/package.json version is right. Otherwise i need a repo.

**Comment by gauzpan** [comment]
@Fank ... I am facing the same problem. The problem occurs when we do npm instaIl in our project so all the depencies are being install and I think that in the typings.json you need to remove the es6-shim registry or remove the line 'typings install' from the scripts inside package.json. This will prevent the typings folder to be created and in typescript 2.0 we have separate @types/file kind of notation. Can you update the package.json to solve this one??

**Comment by monica11** [comment]
@Fank Same issue is still there with the latest version that you mentioned. And I think @gauzpan is right. Please check once.

**Comment by fank** [comment]
Just for understanding, normally on installation packages by using `npm install` 'typings install' won't be triggered. what does it?

**Comment by mikesnare** [comment]
@Fank I'm no npm/package.json guru, but a quick check of all the other node_modules being installed by my package.json shows that this is the only one with a "typings install" script.

All the other node_modules in my build use a "prepublish" script which calls "typings install && npm run build".

**Comment by mikesnare** [comment]
And of those, ALL are ts-node or typings modules/submodules.  No packages outside those modules have any calls to typings at all.

**Comment by fank** [comment]
I still don't understand how "typings-install" is called, but i removed it for now. Lets hope it finally fixes this issue.

**Comment by mikesnare** [comment]
Well.... not 'fixed', just changed.  😄 

I updated to grab the commit you just added, but now I get this:

/app/node_modules/angular2-highcharts/dist/Highcharts.d.ts:
Error:(1, 1) TS6053: File '/app/node_modules/angular2-highcharts/typings/index.d.ts' not found.

I'm going to fork the repo and poke around a bit, but (as I said) I'm no npm/package.json guru so I'm not exactly sure what to do.

**Comment by fank** [comment]
That will be nice, if you find a working solution just open a PR.

**Comment by scandinave** [comment]
After testing with master. The Highcharts lib is missing. After install it with npm, error get off

**Comment by gevgeny** [comment]
So it finally wasn't fixed of it was ?

**Comment by mikesnare** [comment]
It's confirmed working for me and several people here at my site.  @14Muhammad, @tmfcosta, @monica11, and @gauzpan have you tried pulling the latest?

**Comment by gauzpan** [comment]
@mikesnare I did take the pull and plug the code in my project inside node modules and after doing the npm start , I am getting a bunch of errors.

```
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartComponent.d.ts:11:26 
    Cannot find name 'HighchartsChartObject'.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartComponent.d.ts:21:12 
    Cannot find name 'HighchartsChartObject'.
[default]/Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartComponent.d.ts:27:14 
    Cannot find name 'HighchartsOptions'.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartEvent.d.ts:3:14 
    Cannot find name 'HighchartsChartObject'.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartEvent.d.ts:3:38 
    Cannot find name 'HighchartsSeriesObject'.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartEvent.d.ts:3:63 
    Cannot find name 'HighchartsPointObject'.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/ChartEvent.d.ts:3:87 
    Cannot find name 'HighchartsAxisObject'.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/Highcharts.d.ts:1:1 
    File '/Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/typings/index.d.ts' not found.
[default] /Users/gaurav.pandvia/abc/git/newCode/xyz/node_modules/angular2-highcharts/dist/HighchartsService.d.ts:2:17 
    Cannot find name 'HighchartsStatic'.
[default] Checking finished with 9 errors
```

**Comment by gauzpan** [comment]
@mikesnare Earlier what I did to fix the issue that instead of removing typings all together , I just removed the reference to es6-shim which was causing me trouble and that worked for me. @Fank Did you find any other solution to this issue?

**Comment by 14Muhammad** [comment]
@mikesnare .. I'm Still facing the same issue.
`node_modules/angular2-highcharts/typings/globals/es6-shim/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'. typings/globals/core-js/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'. typings/globals/jasmine/index.d.ts(74,9): error TS2375: Duplicate number index signature. typings/globals/jasmine/index.d.ts(128,9): error TS2374: Duplicate string index signature.`
